options = {
    'resize_factor': 0.5,
    'denoise': False,
    'split_factor': 0.25,
    'test_mode': False,
    'colorspace': 'gray',
    'extension': 'png',
    'laplacian': False,
    'median_filter': False,
    'bilateral_filter': False,
    'pre_denoise': False,
    'alpha': 3,
    'rho': 0.05,
    'noise_filter': ['base',False],
    'fill': False,
    'adaptive_model': False,
    'return_bboxes': True,
    'save_img': False,
    'task': 0
}